services:
  test-runner:
    container_name: test-runner
    build:
      context: .
      dockerfile: Dockerfile.test-runner
    volumes:
      - ./reports:/app/reports
    depends_on:
      - selenoid
    environment:
      - SELENIUM_HOST=selenoid
      - SELENIUM_PORT=4444
    networks:
      - selenoid_net

  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - ./browsers:/etc/selenoid/browsers
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENABLE_VNC=true
    networks:
      - selenoid_net

networks:
  selenoid-net:
    name: selenoid_network
    driver: bridge