#version: '3.8'
#
#services:
#  selenoid:
#    image: aerokube/selenoid:latest
#    container_name: selenoid
#    networks:
#      - selenoid-network
#    ports:
#      - "4444:4444"
#    environment:
#      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
#      - OVERRIDE_LOG_OUTPUT_DIR=/opt/selenoid/logs
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./selenoid/browsers.json:/etc/selenoid/browsers.json  # конфиги: browsers.json, etc.
#      - ./video:/opt/selenoid/video
#      - ./logs:/opt/selenoid/logs
#    command: >
#      -conf /etc/selenoid/browsers.json
#      -limit 20
#      -retry-count 3
#      -video-output-dir /opt/selenoid/video
#      -log-output-dir /opt/selenoid/logs
#      -max-timeout 20m
#      -session-attempt-timeout 15m
#      -timeout 10m
#      -service-startup-timeout 10m
#    restart: unless-stopped
#
#  selenoid-ui:
#    image: aerokube/selenoid-ui:latest
#    container_name: selenoid-ui
#    networks:
#      - selenoid-network
#    ports:
#      - "8080:8080"
#    command: --selenoid-uri=http://selenoid:4444
#    depends_on:
#      - selenoid
#    restart: unless-stopped
#
#  testrunner:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: testrunner
#    networks:
#      - selenoid-network
#    volumes:
#      - ./reports:/app/reports
#    environment:
#      SELENIUM_HOST: selenoid
#      SELENIUM_PORT: 4444
#    depends_on:
#      - selenoid
#    # Не нужно открывать порты, если не запускаешь сервис
#    # command: pytest -v
#
#networks:
#  selenoid-network:
#    driver: bridge



networks:
  selenoid-net:
    name: selenoid-net
    external: true

services:
  selenoid:
    networks:
      selenoid-net: null
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid/browsers.json:/etc/selenoid/browsers.json
      - ./video:/opt/selenoid/video
      - ./logs:/opt/selenoid/logs
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR==/opt/selenoid/logs
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "selenoid-net" ]
    ports:
      - "4444:4444"
      - "4445:4445"

  testrunner:
    networks:
      selenoid-net: null
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testrunner
    volumes:
      - ./reports:/app/reports
    depends_on:
      - selenoid