# Dockerfile.test

FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y wget unzip curl && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

COPY . .

ENV SELENIUM_HOST=http://selenoid:4444/wd/hub
ENV ALLURE_RESULTS_DIR=/app/reports/allure-results

CMD ["python", "-m", "pytest"]