[pytest]
addopts =
            -v
            -s
            --alluredir=./reports/allure
            --junitxml=./reports/junit/results.xml
            --clean-alluredir


;allure generate ./reports/allure_raw -o ./reports/generated_reports --clean --single-file